[[d1_databases]]
binding = "DB"
database_name = "kosher-arsenal"
database_id = "5500a5b1-f0a4-4337-af3d-c43ed65aa590"

[[kv_namespaces]]
binding = "CACHE"
id = "c32a746aa15440be982a6f29fc0f901c"

[[kv_namespaces]]
binding = "KV"
id = "048ecdb7e0764988a146ab53ce7393e7"

[[r2_buckets]]
binding = "BLOB"
bucket_name = "kosher-arsenal"